name: Start Opentest

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: github-actions-nodejs
      # You may pin to the exact commit or the version.
      # uses: thonatos/github-actions-nodejs@50c6667f26d2aaa41206e1d43c58682913ad6d71
      uses: thonatos/github-actions-nodejs@v0.1.1
    - uses: actions/checkout@master
    - name: Start Opentest Session
      run: opentest session create --template "Call API Template"
