name: Action Call Opentest

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Set Up .NetCore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.408'
    - uses: actions/checkout@master
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - name: actions/setup-opentest
    - name: Start Opentest Session
      run: opentest session create --template "Call API Template"
