name: Start Opentest

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - uses: actions/checkout@master
    - name: actions/setup-opentest
    - name: Start Opentest Session
      run: opentest session create --template "Call API Template"
