name: Start Opentest

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
        
    - name: Start Opentest
      run: |
        cd opentest/server/
        opentest server
