name: ActionCallAPI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Set Up .NetCore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.408'
        
    - name: Dotnet Restore
      run: |
        dotnet restore src/ApiReservas/
        
    - name: Build with dotnet
      run: |
        dotnet build src/ApiReservas/
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      
    - name: Install Opentest 
      run: |
        npm install opentest -g
        
    - name: Start Script
      run: .github\scripts\startApi.ps1
    
    - name: Api Actors
      run: curl http://localhost:3000/api/actors
      
    - name: Start Test
      run: |
        cd ${{github.workspace}}/opentest/test-repo/templates
        opentest session create --template "Call API Template" --wait
